language: generic
sudo: required # require super user permission
services:
    - docker
        
before_install:
    - docker build -t ravik775/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true ravik775/docker-react npm run test

deploy:
    edge: true
    provider: elasticbeanstalk
    region: "us-east-2"
    app: "docker-react"
    env: "DockerReact-env"
    bucket-name: "elasticbeanstalk-us-east-2-958354931925"
    bucket: "docker-react"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: "$AWS_SECRET_KEY"
