language: node_js
node_js:
  - "stable"
sudo: required # require super user permission
services:
    - docker
        
before_install:
    - docker build -t ravik775/docker-react -f Dockerfile.dev .

script:
    - docker run ravik775/docker-react npm run test -- --coverage

