language: generic
sudo: required # require super user permission
services:
    - docker
        
before_install:
    - docker build -t ravik775/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true ravik775/docker-react npm run test

