version: "3"
services: 
    web:
        build: 
            context: .
            dockerfile: Dockerfile.dev
        ports:
            - "5000:3000"
    test:
        build: 
            context: .
            dockerfile: Dockerfile.dev
        command: ["npm", "run", "test"]